### PR TITLE
fix(ui): make stats component reactive

### PR DESCRIPTION
**Pull request by geigerzaehler**
We make the stats component reactive so that changes in the props are reflected in the rendered dom.

### CODE REVIEW

**Review by xla — APPROVED** [review]
👼 ♊️ 🚅 ⤴️

**Comment by MeBrei** [comment]
When are the stats actually updated without refresh? 
Tried to test it with creating a branch to a project I had open in the app, but the changes were not visible without refreshing.

**Comment by xla** [comment]
> When are the stats actually updated without refresh?

This a chore for the actual ui rendering not for rolling in backend changes afaik.

**Review by MeBrei — APPROVED** [review]

**Comment by geigerzaehler** [comment]
> When are the stats actually updated without refresh?
> Tried to test it with creating a branch to a project I had open in the app, but the changes were not visible without refreshing.

Here’s how you can reproduce the bug:
1. Make sure you have at least one project in the “Following” list
2. Follow another project and wait for it to be tracked successfully
3. If the new project is not added to the end of the list in “Following” it will show the stats from the item it replaced. Same for all other projects that were moved by the new project being inserted.

**Pull request merged**
