### PR TITLE
chore(ci): fail build on eslint warnings

### PR DESCRIPTION
**Pull request by geigerzaehler**
Make the build fail on eslint warnings and fix existing eslint warnings.

Refs #696

### CODE REVIEW

**Comment by rudolfs** [comment]
Refs: https://github.com/radicle-dev/radicle-upstream/issues/696?

**Comment by rudolfs** [comment]
@xla this PR adds more "disable" statements to the issue, hence *refs*. It doesn't resolve it.

**Comment by geigerzaehler** [comment]
@xla, @rudolfs: Could you have a look? The build errors are fixed now.

**Review by rudolfs — DISMISSED** [review]
👍

**Review by xla — APPROVED** [review]
📿 🔢 🍞 🕐

**Review by rudolfs — APPROVED** [review]

**Comment by geigerzaehler** [comment]
@xla: Could you have another look? I had to push a no-op commit to re-trigger the build

**Review by xla — APPROVED** [review]
(〃ω〃)

**Pull request merged**
