### PR TITLE
feat: implement single-sig orgs

### PR DESCRIPTION
**Pull request by rudolfs**
Closes: https://github.com/radicle-dev/radicle-upstream/issues/2084.

Screenshot 2021-07-02 at 17 15 52
Screenshot 2021-07-02 at 17 16 23

### CODE REVIEW

**Comment by juliendonck** [comment]
I'm having a bug where I can't create a multisig org anymore with this PR:

```
{
  "stack": "TypeError: orgFactory.createOrg(address[], uint256) is not a function\n    at Module.submitCreateOrgTx (webpack-internal:///./ui/src/org/contract.ts:55:59)\n    at Module.createOrg (webpack-internal:///./ui/src/org.ts:191:69)\n    at eval (webpack-internal:///./ui/Modal/Org/Create.svelte:676:51)\n    at Generator.next (<anonymous>)\n    at eval (webpack-internal:///./ui/Modal/Org/Create.svelte:659:67)\n    at new Promise (<anonymous>)\n    at __awaiter (webpack-internal:///./ui/Modal/Org/Create.svelte:636:10)\n    at createOrg (webpack-internal:///./ui/Modal/Org/Create.svelte:672:10)\n    at click_handler_3 (webpack-internal:///./ui/Modal/Org/Create.svelte:705:32)\n    at eval (webpack-internal:///./node_modules/svelte/internal/index.mjs:852:41)",
  "message": "orgFactory.createOrg(address[], uint256) is not a function",
  "code": "UnhandledRejection",
  "details": {
    "name": "TypeError"
  }
}
```

**Comment by juliendonck** [comment]
> I'm having a bug where I can't create a multisig org anymore with this PR:
> 
> ```
> {
>   "stack": "TypeError: orgFactory.createOrg(address[], uint256) is not a function\n    at Module.submitCreateOrgTx (webpack-internal:///./ui/src/org/contract.ts:55:59)\n    at Module.createOrg (webpack-internal:///./ui/src/org.ts:191:69)\n    at eval (webpack-internal:///./ui/Modal/Org/Create.svelte:676:51)\n    at Generator.next (<anonymous>)\n    at eval (webpack-internal:///./ui/Modal/Org/Create.svelte:659:67)\n    at new Promise (<anonymous>)\n    at __awaiter (webpack-internal:///./ui/Modal/Org/Create.svelte:636:10)\n    at createOrg (webpack-internal:///./ui/Modal/Org/Create.svelte:672:10)\n    at click_handler_3 (webpack-internal:///./ui/Modal/Org/Create.svelte:705:32)\n    at eval (webpack-internal:///./node_modules/svelte/internal/index.mjs:852:41)",
>   "message": "orgFactory.createOrg(address[], uint256) is not a function",
>   "code": "UnhandledRejection",
>   "details": {
>     "name": "TypeError"
>   }
> }
> ```

Also having trouble anchoring a project now. I think something is broken in the gnosis safe flow

**Comment by juliendonck** [comment]
Was testing this again, now it creates a single signer org when choosing the multi sig option

**Comment by geigerzaehler** [comment]
> I'm having a bug where I can't create a multisig org anymore with this PR:

Fixed 

> Was testing this again, now it creates a single signer org when choosing the multi sig option

Also fixed

Could you have another look?

**Comment by juliendonck** [comment]
> > I'm having a bug where I can't create a multisig org anymore with this PR:
> 
> Fixed
> 
> > Was testing this again, now it creates a single signer org when choosing the multi sig option
> 
> Also fixed
> 
> Could you have another look?

Works! Thanks :)

**Review by geigerzaehler — APPROVED** [review]

**Pull request merged**
