### PR TITLE
feature(proxy): use port with less bind conflicts

### PR DESCRIPTION
**Pull request by geigerzaehler**
Instead of port 8080 we use port 17246 to bind the proxy to. This decreases the likelihood of another services binding to the port.

### CODE REVIEW

**Review by xla — CHANGES_REQUESTED** [review]
Feels like this just moves the problem around. How hard would it be for the application container pass down a random port to the proxy?

**Comment by geigerzaehler** [comment]
> How hard would it be for the application container pass down a random port to the proxy?

It’s a bit more effort since we need to use IPC to communicate the port the the app. We can tackle this later and it should not be a blocker for this PR. It’s all written down in #1189.

**Review by FintanH — DISMISSED** [review]
Happy with this stop-gap since there's an issue to track the actual fix. I imagine this change will help stop people from running into the application not starting for the time being.

**Review by rudolfs — APPROVED** [review]
<3 the low-cost approach!

Screenshot 2020-11-09 at 17 36 55

**Review by rudolfs — APPROVED** [review]

**Review by cloudhead — APPROVED** [review]
I would normally bikeshed on the port number, but not this time :+1:

**Pull request merged**
