### PR TITLE
fix(ui): extend password text

### PR DESCRIPTION
**Pull request by MeBrei**
Contributes to resolving #836 

Adds `Be sure to put this in a safe place!` to the description on the onboarding password screen

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]

**Review by xla — CHANGES_REQUESTED** [review]
This is a strange advise, are we implying to use a password manager?

**Comment by juliendonck** [comment]
> This is a strange advise, are we implying to use a password manager?

@xla Are we? Do you consider a password manager a safe place? If not, then we're not implying that. I don't think it's our job to teach cyber security to our users.

**Review by juliendonck — APPROVED** [review]

**Comment by xla** [comment]
> @xla Are we? Do you consider a password manager a safe place? If not, then we're not implying that. I don't think it's our job to teach cyber security to our users.

That would be a bit much in the context of this field. Yet the wording might help more if we remind the user that they make sure they won't loose "access" to the password.

**Comment by abbey-titcomb** [comment]
This change is just to keep the app copy consistent with what we have in the Figma file.

I don't see how it's strange but am open to alternate suggestions on wording if have some @xla

**Pull request merged**
