### PR TITLE
Move network diagnostics shortcut to ⌘ + 1

### PR DESCRIPTION
**Pull request by rudolfs**
~~Moving from `⌘ + i` to `⌘ + y`, because `⌘ + i` clashes with the dev tools shortcut `option + ⌘ + i` on mac.~~

`⌘ + 1` it is.

And make it available in the production build, because we want users to be able to access the diagnostics to troubleshoot problems on live systems.

Signed-off-by: Rūdolfs Ošiņš <rudolfs@osins.org>

### CODE REVIEW

**Review by geigerzaehler — APPROVED** [review]

**Review by geigerzaehler — CHANGES_REQUESTED** [review]
Ctrl + y is redo. We should find something else or also check for the presence of the option and shift keys when `Ctrl + i` is hit.

**Review by juliendonck — DISMISSED** [review]
🔥

**Comment by rudolfs** [comment]
How about ctrl + 1 then? We can map 1-9 to different internal diagnostics.

**Comment by geigerzaehler** [comment]
> How about ctrl + 1 then? We can map 1-9 to different internal diagnostics.

Sounds good to me

**Review by geigerzaehler — DISMISSED** [review]

**Comment by rudolfs** [comment]
I also removed the JSONTree dep to get rid of these warnings:
```
ui:
  asset bundle.js 18.9 MiB [compared for emit] [big] (name: main)
  asset index.html 4.06 KiB [compared for emit]
  cached modules 7.97 MiB (javascript) 1.37 KiB (runtime) [cached] 1145 modules

  WARNING in ./node_modules/svelte-json-tree/src/JSONKey.svelte
  Module Warning (from ./node_modules/svelte-loader/index.js):
  A11y: A form label must be associated with a control. (17:2)
  15: </style>
  16: {#if showKey && key}
  17:   <label class:spaced={isParentExpanded} on:click>
        ^
  18:     <span>{key}{colon}</span>
  19:   </label>
   @ ./node_modules/svelte-json-tree/src/JSONValueNode.svelte 28:0-39 52:15-22 161:2-9
   @ ./node_modules/svelte-json-tree/src/JSONNode.svelte 25:0-51 158:11-24 210:2-15
   @ ./node_modules/svelte-json-tree/src/Root.svelte 21:0-41 38:16-24 112:2-10
   @ ./ui/Screen/NetworkDiagnostics/WaitingRoom.svelte 31:0-40 147:16-24 470:2-10
   @ ./ui/Screen/NetworkDiagnostics.svelte 37:0-66 308:42-53 343:2-13
   @ ./ui/App.svelte 64:0-68 460:28-46 508:2-20
   @ ./ui/index.ts 1:0-31 2:16-19

  WARNING in ./node_modules/svelte-json-tree/src/JSONNested.svelte
  Module Warning (from ./node_modules/svelte-loader/index.js):
  A11y: A form label must be associated with a control. (56:2)
  54: </style>
  55: <li class:indent={isParentExpanded}>
  56:   <label>
        ^
  57:     {#if expandable && isParentExpanded}
  58:       <JSONArrow on:click={toggleExpand} {expanded} />
   @ ./node_modules/svelte-json-tree/src/JSONObjectNode.svelte 17:0-45 24:18-28 120:2-12
   @ ./node_modules/svelte-json-tree/src/JSONNode.svelte 20:0-53 144:11-25 205:2-16
   @ ./node_modules/svelte-json-tree/src/Root.svelte 21:0-41 38:16-24 112:2-10
   @ ./ui/Screen/NetworkDiagnostics/WaitingRoom.svelte 31:0-40 147:16-24 470:2-10
   @ ./ui/Screen/NetworkDiagnostics.svelte 37:0-66 308:42-53 343:2-13
   @ ./ui/App.svelte 64:0-68 460:28-46 508:2-20
   @ ./ui/index.ts 1:0-31 2:16-19

  2 warnings have detailed information that is not shown.
  Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
  ```
The json output is still readable:
Screenshot 2021-05-28 at 17 37 02

**Review by geigerzaehler — APPROVED** [review]

**Comment by rudolfs** [comment]
Merged via c6975154ca5280d6846a09ec01b5001620a13199.

**Pull request closed without merging**
