### PR TITLE
style(ui): improve modals + add shadows

### PR DESCRIPTION
**Pull request by juliendonck**
- adds a modal component to align styles between all modals
- adds shadows to modal 

Dark mode shadows: 
15c461b3-5046-4f19-86ae-84141497d9b4

### CODE REVIEW

**Review by cloudhead — DISMISSED** [review]

**Review by rudolfs — APPROVED** [review]
LGTM 🚀 

Does the search modal not get a background?
Screenshot 2021-01-12 at 08 50 55

**Comment by brandonhaslegs** [comment]
> Does the search modal not get a background?

I think it should

**Comment by juliendonck** [comment]
> > Does the search modal not get a background?
> 
> I think it should

https://github.com/radicle-dev/radicle-upstream/pull/1510/commits/5ade87b7af9ff5f43c9f81451919c36cb8826eff

**Review by brandonhaslegs — APPROVED** [review]

**Review by rudolfs — APPROVED** [review]

**Comment by juliendonck** [comment]
Merged into master via the cli

**Comment by rudolfs** [comment]
Commit just for reference: https://github.com/radicle-dev/radicle-upstream/commit/57ab2d79cc8573b0edc4ec76bd9cc57d45d29628.

**Pull request closed without merging**
