### PR TITLE
fix(proxy): reintroduce sync on startup

### PR DESCRIPTION
**Pull request by xla**
During the great merges of 2020 we went back to the default of
RunConfig, which does not have sync on startup enabled. This behaviour
is desired for proxies running in "production".

### CODE REVIEW

**Review by kim — APPROVED** [review]
`Default::default()` !

**Review by rudolfs — APPROVED** [review]

**Review by NunoAlexandre — APPROVED** [review]
:honey_pot:

**Review by NunoAlexandre — APPROVED** [review]
:bee:

**Review by rudolfs — APPROVED** [review]

**Review by rudolfs — APPROVED** [review]

**Review by NunoAlexandre — APPROVED** [review]

**Review by FintanH — APPROVED** [review]
:metal:

**Pull request merged**
