### PR TITLE
style(ui): add primary color levels as opacities

### PR DESCRIPTION
**Pull request by brandonhaslegs**
Change primary color levels to work with opacities in preparation for #1803.

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
Can someone check the error page with this change? Just wondering if it still works. I think it should be fine.

**Comment by rudolfs** [comment]
Seems to be working just fine:

Screenshot 2021-06-21 at 14 10 26

Is the halo/border around buttons intentional?

https://user-images.githubusercontent.com/158411/122759909-cb261800-d29a-11eb-9242-27c1b52e70d5.mov

Screenshot 2021-06-21 at 14 11 08

**Review by rudolfs — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
The border was introduced last week sometime. There's an issue for it#2030

**Comment by rudolfs** [comment]
Should we convert all the other colors to RGBa as well for consistency?

**Comment by brandonhaslegs** [comment]
Yep I'll make an issue and do that soon.

**Comment by juliendonck** [comment]
And make all the levels opacity based?

**Comment by rudolfs** [comment]
I was only referring to converting `#5555ff` -> `rgba(85, 85, 255, 1);`.
I don't really care whether the other levels are actually opacity based or not.
If it makes sense from a design perspective then yeah, why not.

**Comment by brandonhaslegs** [comment]
This would break some things if we've ever put a lighter level on a darker level.

**Comment by rudolfs** [comment]
> This would break some things if we've ever put a lighter level

Indeed, I was thinking about this as well. From now on we'll have to keep this in mind. With the previous hex-only implementation we were able to mix any color combination without worrying about this issue.

**Comment by brandonhaslegs** [comment]
I think we can live with this restriction though.

**Pull request merged**
