### PR TITLE
chore(dependencies): Bump dependencies

### PR DESCRIPTION
**Pull request by NunoAlexandre**
Getting started on my new machine, I had to install electron (`npm install electron --save-dev`), which resulted in a bump to the version we use.

### CODE REVIEW

**Comment by NunoAlexandre** [comment]
@xla @rudolfs it seems like I added `package-lock.json`. Is there a reason as to why that wasn't included so far?

**Comment by rudolfs** [comment]
@NunoAlexandre we use `yarn` as the default package manager, not `npm`.

**Comment by rudolfs** [comment]
We also normally do upgrades for the whole UI stack via `yarn upgrade-interactive --latest`. As we'll have to manually check some thing for which we don't have tests (visuals, packaging, etc).

**Comment by NunoAlexandre** [comment]
Running `yarn start` failed because `electron` wasn't installed. The only way I could find to install the electron was via `npm`. How are/have you doing/done it yourselves?

**Comment by rudolfs** [comment]
@NunoAlexandre I think you missed a point from: https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#running-upstream

> Install dependencies: cd radicle-upstream && yarn install.

**Comment by rudolfs** [comment]
Btw. happy to adjust the doc so it's more obvious to newcomers, let me know if you have suggestions on how to restructure it.

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre I think you missed a point from: https://github.com/radicle-dev/radicle-upstream/blob/master/DEVELOPMENT.md#running-upstream
> 
> > Install dependencies: cd radicle-upstream && yarn install.
> 
> So just run `yarn install` and you should be set.

I think I tried `yarn install` but from the `ui` dir :facepalm:

**Pull request closed without merging**
