### PR TITLE
feat(ui): add feedback section in settings

### LINKED ISSUE #873: Add feedback section in settings
[Link to Figma file.](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1%F0%9F%86%99-Radicle-Upstream?node-id=4147%3A7518)

image

### PR DESCRIPTION
**Pull request by juliendonck**
closes #873

### CODE REVIEW

**Review by rudolfs — DISMISSED** [review]

**Review by brandonhaslegs — DISMISSED** [review]
Links should have hover states.

**Comment by cloudhead** [comment]
I don't really like the idea of linking to websites we don't control.. if we lose access to any of them, the app will keep telling users to go there for support.

**Comment by juliendonck** [comment]
> I don't really like the idea of linking to websites we don't control.. if we lose access to any of them, the app will keep telling users to go there for support.

@cloudhead so you'd only send them to the radicle.community then?

cc @abbey-titcomb what do you think?

**Comment by abbey-titcomb** [comment]
IMO, I don't get why we link Twitter. My recommendation would be the following:

Feedback

Submit an issue -> https://github.com/radicle-dev/radicle-upstream
Get in touch directly -> https://radicle.community/c/site-feedback/2 [will devote a category to app feedback]
Join the developer chat -> [insert matrix link]

We don't have a community@monadic.xyz or support@monadic.xyz email so I say we don't include it. IMO, email is fit for more high throughput "user support" which we might not need at this stage. Let's send people to our community channels.

**Comment by cloudhead** [comment]
Yeah I would just send them to `radicle.community`, we can have a special section there for support. I think that's preferrable than asking people to create github accounts and filling our issue list with user issues.

**Comment by abbey-titcomb** [comment]
> Yeah I would just send them to `radicle.community`, we can have a special section there for support. I think that's preferrable than asking people to create github accounts and filling our issue list with user issues.
> EDIT: Plus matrix

So, no linking to issues?

**Comment by juliendonck** [comment]
@abbey-titcomb @cloudhead This is what I did for now. Since we don't have matrix yet, I used the freenode IRC channel. We can then update that when we have matrix. Otherwise this PR is never gonna get merged.

Screenshot 2020-09-15 at 14 04 28

**Review by cloudhead — APPROVED** [review]

**Review by abbey-titcomb — APPROVED** [review]

**Review by abbey-titcomb — APPROVED** [review]

**Pull request merged**
