### PR TITLE
improvement: add org button revamp with <Icon.Plus /> 

### LINKED ISSUE #2073: Use button component for add org button in sidebar
image

This is currently just an SVG. it should use the outline icon button component, and the `plus` icon.

### PR DESCRIPTION
**Pull request by nishit-prasad**
Signed-off-by: Nishit Prasad <prasad.nishit0@gmail.com>

This PR fixes #2073 

Per the discussion [here](https://github.com/radicle-dev/radicle-upstream/issues/2073), the following changes are made:
- [x] Replaced the hardcoded `<svg>` element along with its styles inside `<AddOrgButton />` with simple `<Icon.Plus />`
- [x] `button-transition-big` class style already exists within `<SidebarItem />` component definition. Hence, by default this styling gets inherited in `<AddOrgButton />` component. (Reference [here](https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/Sidebar/SidebarItem.svelte#L68)) 
- [x] Inserted `indicator` prop in the `<SideBarItem />` present within `<OrgList />` component.

Though the `<AddOrgButton />` just has an Icon, it's better to have it like this for the sake of future enhancements/encapsulations as necessary.

Attached below gifs for reference.

**BEFORE:**
ScreenRecord

**AFTER:** (now consistent with other sidebar items)
ScreenRecord

### CODE REVIEW

**Review by brandonhaslegs — COMMENTED** [review]
Nice, thanks for the contribution! I wonder if the `AddOrgButton` component even needs to be a component anymore? @rudolfs what do you think?

**Comment by nishit-prasad** [comment]
That's what I thought too. But again, though the `<AddOrgButton />` just has an Icon, won't it be better to have it like this for the sake of future enhancements/encapsulations as necessary?

**Comment by juliendonck** [comment]
Yeah we definitely don't need the wrapping component now. We can add it back in if we need it.

**Comment by nishit-prasad** [comment]
Sounds good. I will make the change. Thank you!

**Comment by nishit-prasad** [comment]
@brandonhaslegs @juliendonck 
I've pushed a commit that replaced `<AddOrg />` button with `<Icon.Plus />` in `<OrgList />` and removed the `<AddOrg />` component file.
Tested locally and works the same like the above gif.

**Review by brandonhaslegs — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
Ah just noticed your commits aren't signed (git commit -s). We require contributors to sign-off on our DCO for licensing reasons. Could you please do that and force-push the commit after? (Same goes for your other PR).

**Comment by nishit-prasad** [comment]
I do remember doing that, don't know what happened. Let me do it again. Apologies!

**Comment by nishit-prasad** [comment]
@brandonhaslegs 
That's odd because I do remember doing that.

I do see both of my commits signed-off for this PR. Am I missing anything specific? Please advise.

[Link](https://github.com/radicle-dev/radicle-upstream/pull/2094/commits/1f70ab1b108c056931643e6c10db489d08a4d0e2)
Screen Shot 2021-07-04 at 6 14 42 PM

[Link](https://github.com/radicle-dev/radicle-upstream/pull/2094/commits/fb354e5c90ab2fd986dc4f5f94c9a051c2b7013e)
Screen Shot 2021-07-04 at 6 14 52 PM

**Comment by juliendonck** [comment]
> @brandonhaslegs
> Thank you for getting back.
> 
> I do see both of my commits signed-off for this PR. Am I missing anything specific? Please advise.

This is what we're looking for:
Screenshot 2021-07-05 at 10 53 06

You get this by signing your commits with GPG. You can learn more about it [here](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-commits)

**Comment by nishit-prasad** [comment]
@brandonhaslegs 
Ah! Thank you!. I have force pushed commits that are now signed with GPG key. Please let me know if you like all of the past commits to be verified/signed the same way as well.

**Comment by brandonhaslegs** [comment]
Yep, there you go. And yes, all commits have to be signed. Sorry for the long process to get started!

**Review by juliendonck — APPROVED** [review]
Great work, thanks!

**Comment by nishit-prasad** [comment]
No worries. I learned something new. So thank you!
From now onwards, all of my commits will be _signed_ with GPG key.
Let me figure out how to make my old commits signed. Otherwise, I can work on other issues and fix the commits accordingly.

**Review by brandonhaslegs — APPROVED** [review]

**Comment by nishit-prasad** [comment]
Hey @brandonhaslegs, signing off the old commits in the PR changes the SHA as well as rewrites the history which can be annoying for all of us.

Since most recent signed given commit is by definition the sum of all previous commits => which implicitly means that they are signed off on every commit that is reachable from the one I've signed.

So is it okay to go ahead with the merge? If not, then the only simple way I can think of is close this PR and create a fresh PR with my signed commit.

Please advise.

**Comment by nishit-prasad** [comment]
Woah! I just rebased and can see only the _signed_ commits. We're good to go 😄

**Comment by juliendonck** [comment]
Nice work @nishit-prasad. Appreciate the contribution

**Pull request merged**
