### PR TITLE
style(ui): tweak repo selector

### PR DESCRIPTION
**Pull request by rudolfs**
Based on feedback from @cloudhead:
  - show only selected revision, remove handle/peer
  - make opened dropdown fit longer revisions, limit size with max-width

Based on feedback from @juliendonck:
  - remove `PeerId` from expanded dropdown -- we can already distinguish peers based on the icon

Closes: https://github.com/radicle-dev/radicle-upstream/issues/570.

New (NB: there is a hover background color which doesn't show in the gif):
rev

Old:

before

### CODE REVIEW

**Comment by cloudhead** [comment]
> remove PeerId as we can already distinguish peers based on the icon

We can't actually. The icon is derived from the RadUrn :)

**Comment by juliendonck** [comment]
> > remove PeerId as we can already distinguish peers based on the icon
> 
> We can't actually. The icon is derived from the RadUrn :)

You're saying it will only be the randomHashId? No avatar and no handle?

**Comment by cloudhead** [comment]
> @cloudhead You're saying it will only be the randomHashId? No avatar and no handle?

Not at all, I'm saying we can't distinguish peers based on the icon alone.

**Comment by juliendonck** [comment]
> > @cloudhead You're saying it will only be the randomHashId? No avatar and no handle?
> 
> Not at all, I'm saying we can't distinguish peers based on the icon alone.

But in the dropdown you'd see the icon and handle. Which should be more than enough.

**Comment by rudolfs** [comment]
Here's the updated version after IRL feedback from @cloudhead & @juliendonck (note: gif still doesn't show hover background, but it is there):
v2

**Comment by FintanH** [comment]
I think I missed something... Why's there an issue with keeping the PeerId hash as part of the name? As mentioned, it would uniquely distinguish a user's machine if they had multiple.

The icons will surely overlap at some stage too right? Which is not as likely with a hash :)

**Comment by rudolfs** [comment]
> I think I missed something... Why's there an issue with keeping the PeerId hash as part of the name? As mentioned, it would uniquely distinguish a user's machine if they had multiple.

> The icons will surely overlap at some stage too right? Which is not as likely with a hash :)

@FintanH: @juliendonck, @cloudhead and I had a conversation offline and settled on only showing `PeerId`s if there are multiple peers for a user. If there's only one peer per user we want to hide the `PeerId` so the UI looks cleaner.

For β1 there won't be support for multiple peers per user in Upstream, hence the formatting was split out in a separate issue: https://github.com/radicle-dev/radicle-upstream/issues/683.

**Comment by FintanH** [comment]
> For β1 there won't be support for multiple peers per user in Upstream, hence the formatting was split out in a separate issue: #683.

I don't see how you could prevent this 🤔 that's stopping a person using Upstream on more than one machine

**Comment by rudolfs** [comment]
> I don't see how you could prevent this 🤔 that's stopping a person using Upstream on more than one machine

Will the functionality for transferring keys to another machine to set up the same identity be already integrated for β1?

**Comment by FintanH** [comment]
> Will the functionality for transferring keys to another machine to set up the same identity be already integrated for β1?

Transferring keys has nothing to do with it. It would be two or more machines attesting that they're the same identity and reaching a quorum. If all goes well that should be possible given the discovery and replication work.

**Comment by cloudhead** [comment]
> Transferring keys has nothing to do with it. It would be two or more machines attesting that they're the same identity and reaching a quorum. If all goes well that should be possible given the discovery and replication work.

This would require manual work from the user though at this stage. Upstream doesn't support updating an identity with an extra device currently, so the only way you'd end up in that situation is if you really know what you're doing.

**Comment by FintanH** [comment]
> This would require manual work from the user though at this stage. Upstream doesn't support updating an identity with an extra device currently, so the only way you'd end up in that situation is if you really know what you're doing.

Pesky super users!

**Pull request merged**
