### PR TITLE
 fix(ui) prevent images in markdown from overflowing

### PR DESCRIPTION
**Pull request by Tbaut**
Same as https://github.com/radicle-dev/radicle-upstream/pull/1361 but signed :)

A tiny fix to go from:
image

to:
image

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]

**Review by MeBrei — APPROVED** [review]

**Review by FintanH — APPROVED** [review]
Thanks for signing @Tbaut :raised_hands:

**Review by FintanH — CHANGES_REQUESTED** [review]
Hey @Tbaut I hate to be the bearer of bad news :sweat_smile: But what you did is GPG signed the commit. This is actually different from the legal sign off of a commit which looks like:
```
Signed-off-by: Fintan Halpenny <fintan.halpenny@gmail.com>
```

Since this is on us for our lack of documentation, would you be willing to have a call with me and we can get it sorted out? It would help with documentation of this process on my side too :)

**Review by FintanH — APPROVED** [review]
:tada: We did it!

**Review by rudolfs — APPROVED** [review]

**Review by MeBrei — APPROVED** [review]

**Comment by FintanH** [comment]
Ok, there's something funky about remotes and a particular test as we can see here https://github.com/radicle-dev/radicle-upstream/pull/1396. Either an administrator of upstream merges this or we approve #1396 and merge it since it still contains @Tbaut's commit that is signed.

**Pull request merged**
