### PR TITLE
refactor(ui): keyboard shortcuts modal overhaul

### LINKED ISSUE #832: Overhaul keyboard shortcuts page
- [ ] use new floating modal style
- [ ] add `Keyboard shortcuts` title
- [ ] add illustration
- [ ] wording changes
- [ ] update colors
- [ ] update font styles
Screenshot 2020-08-28 at 10 02 28

### PR DESCRIPTION
**Pull request by MeBrei**
Closes #832

### CODE REVIEW

**Review by rudolfs — CHANGES_REQUESTED** [review]
Looks amazing!

Blockers:
- [ ] clicking outside the modal doesn't close it
- [ ] when opening shortcuts on top of another modal (like project creation), escaping from shortcuts also closes the underlying modal (this works correctly with search)

Nit:
- we should use rem everywhere instead of px: https://daniellamb.com/experiments/px-to-rem-calc/

**Comment by MeBrei** [comment]
> * [ ]  when opening shortcuts on top of another modal (like project creation), escaping from shortcuts also closes the underlying modal (this works correctly with search)

I have tried to debug this. It seems like the `event.target` for the escape key down event is not set properly. For the search modal it points to the search modal itself, for the keyboard shortcuts it points to the profile page.

**Comment by rudolfs** [comment]
@MeBrei: I think you just have to implement your own `esc` key handling in the screen, it needs to pass a `hide` event to the parent, see how it's done in search:
https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/Component/SearchModal.svelte#L33
https://github.com/radicle-dev/radicle-upstream/blob/master/ui/DesignSystem/Component/ModalOverlay.svelte#L51

**Review by rudolfs — APPROVED** [review]

**Review by xla — APPROVED** [review]
🌀 🚥 👑 🏪

**Review by rudolfs — APPROVED** [review]

**Review by brandonhaslegs — APPROVED** [review]

**Pull request merged**
