### PR TITLE
Change "display name" error to "project name"

### PR DESCRIPTION
**Pull request by iamrohitanshu**
error for empty project name field should say "project name" instead of "display name" #1959

Signed-off-by: Rohitanshu Kumar <iamrohitanshu@gmail.com>

### CODE REVIEW

**Review by brandonhaslegs — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
Nice, thanks @iamrohitanshu!

**Comment by rudolfs** [comment]
Thanks for the contribution @iamrohitanshu!

We require contributors to sign-off (git commit -s) on our [DCO](https://github.com/radicle-dev/radicle-upstream/blob/master/DCO) for licensing reasons. Could you please do that and force-push the commit after?

**Comment by iamrohitanshu** [comment]
Hi @rudolfs !
I'm new here. As I understood I had to add a line at the end of the message saying 'Signed-off-by', which I did.
But I have no idea how to force push, as all I could find online included command lines, but I don't know where to execute them as I have not yet installed git locally on my computer.
Can you guide me regarding the force push please?

**Comment by rudolfs** [comment]
> I'm new here. As I understood I had to add a line at the end of the message saying 'Signed-off-by', which I did.
But I have no idea how to force push, as all I could find online included command lines, but I don't know where to execute them as I have not yet installed git locally on my computer.

Ah, that's interesting, I don't think we ever had anyone contribute via the github UI before. I think in this case it would be okay if you just add a comment here with your `Signed-off-by:  Name <email>` message. And I'll add it to the commit when I merge.

**Comment by iamrohitanshu** [comment]
Okay, thank you. I'm adding a new comment for signing-off.

**Comment by iamrohitanshu** [comment]
Signed-off-by: Rohitanshu Kumar <iamrohitanshu@gmail.com>

**Comment by geigerzaehler** [comment]
Merged  in 64881cdb332be49e8e6122368a532632337a060f. Thanks for your contribution @iamrohitanshu!

**Comment by iamrohitanshu** [comment]
Thank you everyone!

**Pull request closed without merging**
