### PR TITLE
feat(ui): add a loading state to create project button

### PR DESCRIPTION
**Pull request by sarahscott**
This isn't a permanent solution because the loading time for a big project can be very tedious. We should work toward something on the project screen itself, or maybe pop to the user profile and add some kind of loading indicator to the project within the list. This PR at least disables the button so the user can't click it a bunch of times.

Related to #512 (doesn't totally fix it though)

createproj

### CODE REVIEW

**Comment by juliendonck** [comment]
@sarahscott Was chatting with @brandonhaslegs about this. Maybe we can just grey out the button but keep the text (no spinner in the button) and just change the cursor to `waiting`.

**Comment by rudolfs** [comment]
> Maybe we can just grey out the button but keep the text (no spinner in the button) and just change the cursor to waiting.

@juliendonck you mean the cursor when you hover the button?

**Comment by juliendonck** [comment]
No the whole time it's loading.

**Comment by xla** [comment]
@juliendonck Can you have another look?

**Comment by rudolfs** [comment]
@xla I think @juliendonck meant the cursor should switch to `waiting` if you're anywhere on the screen, not only when hovering the button.

**Comment by juliendonck** [comment]
Yeah i actually think this won't work. Cause I can still click on other things while it's loading. We'd need to lock the UI while loading and if that's the case then I think we're better of trying to speed this up or putting the user on the next page and doing the loading of the content there.

**Comment by xla** [comment]
> Yeah i actually think this won't work. Cause I can still click on other things while it's loading. We'd need to lock the UI while loading and if that's the case then I think we're better of trying to speed this up or putting the user on the next page and doing the loading of the content there.

Agreed with that sentiment.

**Comment by xla** [comment]
We still track the issue in #512 - this is not an adequate fix. Closing. :<

**Pull request closed without merging**
