### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by geigerzaehler**
Includes an update of marked from `v2` to `v3` ([changelog][1]). The
breaking changes don’t affect us.

Includes a [major update of Electron][2]. This update does not have any
breaking changes except for a major update in Chromium

[1]: https://github.com/markedjs/marked/releases/tag/v3.0.0
[2]: https://www.electronjs.org/releases/stable#15.0.0

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]
utACK

Do you remember why you pinned `"multibase": "=4.0.4"`?

**Comment by geigerzaehler** [comment]
> Do you remember why you pinned `"multibase": "=4.0.4"`?

The package of v4.0.5 was broken but v4.0.6 seems to work again. I’ll fix it.

**Comment by geigerzaehler** [comment]
Turns out that a couple of things were broken by the Electron and Cypress upgrade. I added another commit that fixes these issues. Here are the commit details:

After the upgrades to Electron and Cypress we need to fix our cookie
handling.

* Electron seems to have changed their cookie handling without notice.  We now have to set the `SameSite=None` attribute for cookies which  also requires the `Secure` attribute. Fixes #1197.

* Cypress now has stricter cookie parsing when using `cy.setCookie()`.  This means we have to properly extract the cookie value and ignore the  attributes.

* The session endpoint was not guarded properly with the authentication  token. We fixed that.

**Comment by rudolfs** [comment]
There are still some type errors in the build.

**Comment by geigerzaehler** [comment]
Reverted the check for the session endopint. It doesn’t work. We need to fix this as part of the architecture migration.

**Review by rudolfs — APPROVED** [review]
utACK

**Pull request merged**
