### PR TITLE
fix(ui): always tracked toggle for projects

### LINKED ISSUE #1045: Follow button resets when refreshed
When following a project from another user, the state of the Follow button doesn't hold when I refresh the page or navigate back to it.

image

_Before click_

image

_After click_

image

_After refresh_

### PR DESCRIPTION
**Pull request by xla**
Until we introduce explicit untracking of projects, whenever we show
a project page it is inherently tracked. Therefore the track toggle
should be in tracked state and the unfollow action disabled.

Closes #1045

***
2020-10-16-094442_1738x1408_scrot

### CODE REVIEW

**Review by NunoAlexandre — APPROVED** [review]

**Comment by brandonhaslegs** [comment]
Maybe should just remove the button until you can interact with it? Just having this network icon in a grey box that's not clickable will be pretty confusing.

**Comment by juliendonck** [comment]
I wonder if it's not better having a tooltip explaining that you can't unfollow at the moment then to remove the functionality entirely.

**Comment by FintanH** [comment]
What's this button even for? :joy:

**Comment by xla** [comment]
> What's this button even for? joy

@FintanH To untrack a project at the point we have it that functionality supported.

**Comment by FintanH** [comment]
> To untrack a project at the point we have it that functionality supported.

Does that mean remove it from your device completely?

**Comment by xla** [comment]
> Does that mean remove it from your device completely?

TBD I guess, but I assume something along those lines. As currently "tracking" is equivalent to having a subtree in your monorepo `refs`.

**Comment by FintanH** [comment]
Somebody call me when we need this :call_me_hand:

**Comment by xla** [comment]
Following up on the discussions we had, the inactive toggle is always expanded and says "Following":

2020-10-16-094442_1738x1408_scrot

When testing it in conjunction with the peer selector there is some funkiness with z-indexing so the selector now expands to the left:

2020-10-16-094452_1738x1408_scrot

**Comment by rudolfs** [comment]
There's a weird border on hover:

Screenshot 2020-10-16 at 09 50 46
Screenshot 2020-10-16 at 09 50 50
vs non-hover

Screenshot 2020-10-16 at 09 50 58
Screenshot 2020-10-16 at 09 50 54

**Comment by rudolfs** [comment]
I can still follow/unfollow my project, the button isn't disabled. Was that behaviour also discussed, if so, what was the outcome?

but

**Comment by xla** [comment]
> I can still follow/unfollow my project, the button isn't disabled. Was that behaviour also discussed, if so, what was the outcome?

Yeah just discovered that, will fix and see if I can tame the border/box-shadow.

**Comment by rudolfs** [comment]
There's still a 1px border on hover, I think it should not be there:
border

This removes it:
```diff
diff --git a/ui/DesignSystem/Component/TrackToggle.svelte b/ui/DesignSystem/Component/TrackToggle.svelte
index 7edb809..ef4f126 100644
--- a/ui/DesignSystem/Component/TrackToggle.svelte
+++ b/ui/DesignSystem/Component/TrackToggle.svelte
@@ -42,12 +42,10 @@
   .toggle.hover {
     border: 1px solid var(--color-secondary-level-2);
     background-color: var(--color-secondary-level-2);
-    box-shadow: 0 0 0 1px var(--color-secondary-level-2);
   }
   .toggle.active {
     border: 1px solid var(--color-secondary-level-1);
     background-color: var(--color-secondary-level-1);
-    box-shadow: 0 0 0 1px var(--color-secondary-level-1);
   }
   .toggle.tracking {
     border: 1px solid var(--color-foreground-level-3);
@@ -57,18 +55,15 @@
   .toggle.tracking.hover {
     border: 1px solid var(--color-foreground-level-2);
     background-color: var(--color-foreground-level-2);
-    box-shadow: 0 0 0 1px var(--color-foreground-level-2);
     color: var(--color-foreground-level-6);
   }
   .toggle.tracking.hover.warning {
     color: var(--color-background);
     border: none;
-    box-shadow: none;
   }
   .toggle.tracking.active {
     border: 1px solid var(--color-foreground-level-2);
     background-color: var(--color-foreground-level-2);
-    box-shadow: 0 0 0 1px var(--color-foreground-level-2);
     color: var(--color-foreground-level-4);
   }
   .left {
```

**Review by cloudhead — APPROVED** [review]

**Review by rudolfs — APPROVED** [review]
Neat!

**Comment by brandonhaslegs** [comment]
Maybe should change the cursor on the button to `not-allowed` and add a tooltip that says why I can't unfollow a project.

**Review by cloudhead — APPROVED** [review]

**Comment by xla** [comment]
> Maybe should change the cursor on the button to `not-allowed` and add a tooltip that says why I can't unfollow a project.

Captured in #1061

**Pull request merged**
