### PR TITLE
fix(proxy): quit app when render process crashes

### LINKED ISSUE #1352: Resource cleanup on crash
So I didn't have OpenGL which led me to having a crashed application:
```
(radicle-upstream:1764): GLib-GIO-ERROR **: 10:06:55.349: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)
```

I believe this ones on me and my NixOS set up. HOWEVER, none of the resources are cleaned up:
```
haptop    1782  0.1  0.2 417408 47108 pts/2    S    10:06   0:00 /home/haptop/.cache/appimage-run/3c717cb0fbb6b9e5e185890c8ffba853cc7b1948bd6433efcf8e13fc6d49199c/radicle-upstream --type=zygote --no-zygote-sandbox
haptop    1784  0.0  0.2 417408 46864 pts/2    S    10:06   0:00 /home/haptop/.cache/appimage-run/3c717cb0fbb6b9e5e185890c8ffba853cc7b1948bd6433efcf8e13fc6d49199c/radicle-upstream --type=zygote
haptop    1786  0.0  0.0 417408  8276 pts/2    S    10:06   0:00 /home/haptop/.cache/appimage-run/3c717cb0fbb6b9e5e185890c8ffba853cc7b1948bd6433efcf8e13fc6d49199c/radicle-upstream --type=zygote
haptop    1821  3.8  0.6 789872 111112 pts/2   Sl   10:06   0:00 /home/haptop/.cache/appimage-run/3c717cb0fbb6b9e5e185890c8ffba853cc7b1948bd6433efcf8e13fc6d49199c/radicle-upstream --type=gpu-process --field-trial-handle=11828802767480902528,6833740724110739264,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --gpu-preferences=OAAAAAAAAAAgAAAQAAAAAAAAAAAAAAAAAABgAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAA== --shared-files
haptop    1824  1.0  0.2 1400700 36708 pts/2   Sl   10:06   0:00 /home/haptop/.cache/appimage-run/3c717cb0fbb6b9e5e185890c8ffba853cc7b1948bd6433efcf8e13fc6d49199c/resources/proxy
```

and so a restart of my app will hit the bluescreen of death.

### PR DESCRIPTION
**Pull request by geigerzaehler**
We quit the app when the proxy process goes away unexpectedly.

Note that the `render-process-gone` event is not triggered if the render process exits because the main window is closed.

To test this, start the app and kill the `electron` process that has the argument `--type=render`.

Fixes #1352

### CODE REVIEW

**Comment by xla** [comment]
Would that prevent the BSOD to be shown?

**Comment by geigerzaehler** [comment]
> Would that prevent the BSOD to be shown?

Not sure what you mean. But if the render process crashes there is no window to show a blue screen.

**Review by xla — APPROVED** [review]
♠️ 🆗 🍏 💳

**Review by FintanH — APPROVED** [review]

**Review by rudolfs — APPROVED** [review]
Works on my mac! 🚀 

Just an observation: on `master` after killing the renderer, I can manually restart it by closing the window and reopening, without shutting the whole app down. With this change once the renderer is gone, the app quits.

**Pull request merged**
