### PR TITLE
Add new color theme

### PR DESCRIPTION
**Pull request by brandonhaslegs**
Added new `h4x0r` color theme.

image

image

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
Hey I'm trying to add a new color theme, but I'm getting an error. I added the new option everywhere where I thought I had to but I must have missed something.

```{
  "code": "SessionSettingsUpdateFailure",
  "message": "Failed to update settings: Something went wrong",
  "source": {
    "code": "UnknownException",
    "message": "Something went wrong",
    "details": {
      "message": "Something went wrong",
      "variant": "INTERNAL_ERROR"
    }
  }
}```

**Comment by xla** [comment]
> Hey I'm trying to add a new color theme, but I'm getting an error. I added the new option everywhere where I thought I had to but I must have missed something.

Do you have the logs from the proxy?

**Review by geigerzaehler — APPROVED** [review]

**Review by NunoAlexandre — DISMISSED** [review]
Much hacker, Brandon :robot:

**Review by geigerzaehler — APPROVED** [review]
Still looking good

**Comment by rudolfs** [comment]
Merged via: e097dd715f18ae641b574e669d59c56f07a4ec96.

**Pull request closed without merging**
