### PR TITLE
feat(proxy): Generate random cookie values

### LINKED ISSUE #1090: Unsealed keystore cookie
To add some security, unsealing the keystore should set a cookie, which needs to be part of every subsequent request.  

# Flow
1. `POST /keystore` or `POST /keystore/unseal` request is sent to the API (via onboarding or unlock flow)
2. on success, a cookie is created, stored in the `Context` and sent in the header of the reply via `Set-Cookie`
3. Electron stores and sends the cookie on all subsequent requests
4. in proxy the `with_unsealed_guard` checks if the right cookie was provided, otherwise returns `FORBIDDEN` (it should maybe also seal the keystore, but this will not be part of the first iteration)

Depends on #1083

### PR DESCRIPTION
**Pull request by MeBrei**
Closes #1090

### CODE REVIEW

**Review by geigerzaehler — DISMISSED** [review]
:clap:

One thing we could consider is using the term “(auth) token” instead of “cookie” or “cookie value”. This is a more widely used terminology. See for example [“What is token-based authentication”](https://stackoverflow.com/questions/1592534/what-is-token-based-).authentication

**Review by xla — CHANGES_REQUESTED** [review]
The cookie value is a session secret, it would be favourable to move the creation of these secrets into the session module.

**Comment by MeBrei** [comment]
> The cookie value is a session secret, it would be favourable to move the creation of these secrets into the session module.

I am not opposed to extracting functions for creating and setting the token. The token is somewhat detached from the session though. It get's set directly in the `Context` (session is set in the store) and when onboarding the token get's created before the session is initialized, as there are 2 requests now. First a request to create the key store (and setting the token) and a second one to create the identity. 
SO an alternative could be to move the functions into `context.rs`, but with the current set up I'd personally leave them in `keystore.rs`. Might be that #999 moves some things around.

**Comment by xla** [comment]
> SO an alternative could be to move the functions into `context.rs`, but with the current set up I'd personally leave them in `keystore.rs`. Might be that #999 moves some things around.

As long as we put things in the right place in #999 I'm fine with it. It's just not a good sign to have logic/lib code in the http layer which should be only concerned with translating domain logic into and from HTTP.

**Review by xla — APPROVED** [review]
🐅 ⚪️ 🗄 🐍

**Review by geigerzaehler — APPROVED** [review]

**Review by rudolfs — APPROVED** [review]

**Pull request merged**
