### PR TITLE
refactor(proxy): remove providers

### PR DESCRIPTION
**Pull request by FintanH**
We didn't end up using the providers approach. We should remove it as it
isn't needed and we don't want to encourage anyone to use it.

### CODE REVIEW

**Review by xla — APPROVED** [review]
🔆 🍄 🕞 🏯

**Review by NunoAlexandre — APPROVED** [review]
Ouch :sob:

**Comment by FintanH** [comment]
> Ouch

It was my fault sending you down that path :'(

**Comment by NunoAlexandre** [comment]
> > Ouch
> 
> It was my fault sending you down that path :'(

No worries mate, having a working product is all that matters :heart:

**Pull request merged**
