### PR TITLE
update radicle-link to 2022-02-08

### PR DESCRIPTION
**Pull request by geigerzaehler**

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]
🤞

**Comment by rudolfs** [comment]
We should do https://github.com/radicle-dev/radicle-upstream/issues/2722 before merging this.

**Comment by rudolfs** [comment]
I tested this with 2 devnet peers locally and everything seems to work. I could replicate projects, commits and patches. The peers show up in the respective peer selectors like they should. Didn't test this with a peer <-> seed <-> peer setup, yet.

**Comment by rudolfs** [comment]
> Test case for a succesful migration
> 
> 1. Compile the proxy with the legacy tracking
> 2. Create a maintainer peer M with a project
> 3. Create a peer A that follows the project and has forked it
> 4. Create a peer B that follows the project (without forking it) and tracks A
> 5. Ensure that A and B receive updates from M and that B receives updates from A
> 6. Compile the proxy with the new tracking and restart the peers
> 7. Ensure that we can browse the source for all peers as before
> 8. Ensure that we can have A and B track the maintainer again and B track A
> 9. Ensure that A and B receive updates from M and that B receives updates from A

Getting errors after step 6:
  - M starts without problems
  - A starts and the project shows up in the project list, but when clicking on the project I get:
 ```
we could not find the 'refs/namespaces/hnrkjrmw8ihwbuck74odwofwoftqkgauzzwyo/refs/remotes/hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe/heads/main', variant: INTERNAL_SERVER_ERROR, err: Rejection(State(MissingRef { reference: Reference { remote: Some(hydgo86673kinqy6nkf1s4zgp5gxicppthb1uabtszfe48e65r8ppe), category: Heads, name: RefLike("main"), namespace: Some(Namespace(Urn { id: Oid(922e87af2819b15dd4074816902c5ca36277bd01), path: None })) } }))
```
- B starts up, but the project list doesn't show the project anymore and shows this error:
```
cannot find default branch, project_urn: rad:git:hnrkjrmw8ihwbuck74odwofwoftqkgauzzwyo, err: NoDefaultBranch { name: "mm", urn: Urn { id: Oid(922e87af2819b15dd4074816902c5ca36277bd01), path: None } }
```

**Comment by geigerzaehler** [comment]
I’ve [posted](https://lists.sr.ht/~radicle-link/dev/%3Cb74038d57018c990d3b1d4d44f75383ebbb05dc9.camel%40axiom.fm%3E) about the issue with the default branch missing on the link mailing list

**Comment by geigerzaehler** [comment]
I tested 2022-02-15 and the migration works. This is good to go.

**Review by rudolfs — APPROVED** [review]

**Pull request merged**
