### PR TITLE
fix(ui): don't show stats that equal zero

### PR DESCRIPTION
**Pull request by rudolfs**
This is a workaround for #1223, until we figure out the underlying issue in surf.

- missing branches in project screen
  Screenshot 2020-11-20 at 06 12 22
- missing branches in "Following" tab
  Screenshot 2020-11-20 at 06 13 03
- all stats available in "Following" tab
  Screenshot 2020-11-20 at 06 13 14
- all stats available in project screen
  Screenshot 2020-11-20 at 06 13 18

### CODE REVIEW

**Comment by juliendonck** [comment]
> * missing branches in project screen

Can't we just fake `1 branch` here? THere's always 1 branch, right?

**Comment by rudolfs** [comment]
> Can't we just fake 1 branch here? THere's always 1 branch, right?

There's always at least one, but it could also be more than one.
I think it's worse if we always show "1 branch", but the revision selector has three, for example.

We should really fix the underlying issue in surf if we want to do this proper.

**Review by geigerzaehler — APPROVED** [review]

**Review by juliendonck — APPROVED** [review]
Ok makes sense

**Review by xla — CHANGES_REQUESTED** [review]
Can we avoid the heavy bools in the markup and have a single flag to show or not show stats?

**Comment by rudolfs** [comment]
> Can we avoid the heavy bools in the markup and have a single flag to show or not show stats?

@xla you mean show all stats or show none? Does it make sense if we can show the other stats, and considering that this is a short-lived workaround which we can remove once the underlying issue is fixed?

**Comment by xla** [comment]
> @xla you mean show all stats or show none? Does it make sense if we can show the other stats, and considering that this is a short-lived workaround which we can remove once the underlying issue is fixed?

Is there ever the case where we get 0 branches, but have a number for the contributors?

**Comment by rudolfs** [comment]
> Is there ever the case where we get 0 branches, but have a number for the contributors?

Yes, that's why I added the screenshots in the description ☝️ 

The branches are 0 in this case:
  - Screenshot 2020-11-20 at 11 24 04
  - Screenshot 2020-11-20 at 11 24 09

**Review by xla — APPROVED** [review]
🏦 📜 🍼 🏓

**Review by cloudhead — APPROVED** [review]
Nice!

**Pull request merged**
