### PR TITLE
feat(ui): use Twitter svg emojis in Avatar component

### LINKED ISSUE #231: Choice of emoji set for avatar generation
To guarantee that every user on any OS would get a consistent avatar generated and displayed it would make sense to use a custom emoji set then to rely on the OS's system fonts.

Here are some possible options for that:
- https://twemoji.twitter.com/
- https://www.joypixels.com/

cc @brandonhaslegs @cloudhead

### PR DESCRIPTION
**Pull request by rudolfs**
I got tired of the emoji alignment issues.

The implementation is based on this discussion: https://github.com/radicle-dev/radicle-upstream/issues/231#issuecomment-604914935.

Screenshot 2020-05-04 at 20 58 55
Screenshot 2020-05-04 at 20 59 09
Screenshot 2020-05-04 at 20 59 17

Closes #231, #290.

### CODE REVIEW

**Comment by sarahscott** [comment]
Screen Shot 2020-05-04 at 5 47 39 PM


epic LOC count there; looks great for me!

**Comment by rudolfs** [comment]
> Is it really necessary that we pull in all these files? Esp. these thousands of binary files and what looks like the repositories documentation and tooling files.

I think we won't get around of pulling in the SVGs, as the npm package doesn't have them. If we don't include the SVGs then Upstream have emojis while offline.

I could delete the rest of the files, but we might have to keep the LICENCE around and add a line of attribution to our documentation.

I kept everything initially for the reason that it is a dependency that usually goes into a `vendor` dir and I find it easier to spot mistakes when doing an upgrade of the dependency when all of the files are present.

**Comment by xla** [comment]
> Alternatively we can clone their repo in our org and add it as a submodule to this repo.

I think something along those lines might be better, otherwise having all these files tracked in our repo is a bit of a burden.

**Comment by rudolfs** [comment]
Just had a discussion with @juliendonck: there is another option: just cherry-picking SVGs to cover our emoji whitelist. This would add 538 SVGs to the repo.

The downside would be that we wouldn't be able to use this subset for user input like issue/revision titles, bodies and show them when viewing file content, because it wouldn't cover all the possible emojis.

If we only use the SVG emojis for avatars, in all other places the regular font-based emojis would be displayed.

**Comment by rudolfs** [comment]
So our options are:

1) adding all of the SVGs to this repo
    - adds 3248 files / 14M
    - would be in the repo history forever
    - every update would bloat the repo size
    - we can use all of the emojis in both avatars as well as texts

2) picking only the whitelisted emojis:
    - can't use it for other emoji use-cases (texts, user input)
    - adds 538 files / 1,4M
    - takes effort to hand-pick and update them
    - would be in the repo history forever
    - every update would bloat the repo size

3) add as git submodule
    - would have to find a way to do a shallow clone otherwise CI and the packaged app size could be affected (the twemoji repo weighs 861M)
    - added complexity for dev/CI setup
    - the Upstream repo stays lean
    - we can use all of the emojis in both avatars as well as texts

@cloudhead any thoughts?

**Comment by rudolfs** [comment]
I also wonder if this is enough for proper attribution: https://github.com/radicle-dev/radicle-upstream/blob/c89febc94a90c49b651075875ea6028f9ddb9004/README.md#attribution and whether we need to add the licenses of the emojis and fonts somewhere in the repo?

**Comment by cloudhead** [comment]
I agree that we shouldn't check all these files in. A sub-module could work, or we could create an npm package and depend on it.

**Comment by rudolfs** [comment]
Added Twemoji as npm package, the source lives in this repo: https://github.com/radicle-dev/twemoji-svg-assets

The assets are copied via a `postinstall` script into `public/twemoji` whenever `yarn install` is run: https://github.com/radicle-dev/twemoji-svg-assets/blob/master/package.json#L10.

We should test if emojis:
  - [ ] work on Linux
  - [ ] work on macOS
  - [ ] work on CI

**Pull request merged**
