### PR TITLE
fix: remove pending & rejected transactions from transaction list

### LINKED ISSUE #1970: Pending transactions should show up as pending instead of normal
In the wallet, pending transactions also show up as normal transactions, basically showing up twice

### PR DESCRIPTION
**Pull request by juliendonck**
closes #1970 
Signed-off-by: Julien Donck <hello@juliendonck.com>

### CODE REVIEW

**Comment by brandonhaslegs** [comment]
The pending transaction should only show up in one section, not both.
image

**Review by brandonhaslegs — DISMISSED** [review]
image
Pending transaction should only show up in the pending section, not in both.

**Comment by brandonhaslegs** [comment]
Okay I was on the wrong branch. But another thing: I tried to do it again and ended up with two "Claim Radicle Identity" transactions. Even though this is the result of connecting two different wallets. Shouldn't the transactions not carry over when I connect a new wallet?

image

**Comment by juliendonck** [comment]
> Okay I was on the wrong branch. But another thing: I tried to do it again and ended up with two "Claim Radicle Identity" transactions. Even though this is the result of connecting two different wallets. Shouldn't the transactions not carry over when I connect a new wallet?
> 
> image

Yeah this is something about transactions persisting, we know this happens and will fix this in the next cycle when we take some time to clean up the ethereum code.

**Review by geigerzaehler — APPROVED** [review]

**Comment by geigerzaehler** [comment]
Merged in 79dd6af895c6b62270411f06133be706dc42089a

**Pull request closed without merging**
