### PR TITLE
refactor(proxy): drop warp documentation

### LINKED ISSUE #846: Drop warp documentation
Originally we wanted to have a self-documenting API, we came a long way, but the overhead it causes to keep the docs/playground up-to-date is significant. Especially now as things are moving a lot, it's not giving us enough in return. This also means we can depend on warp mainline again and don't have to maintain a fork.

### PR DESCRIPTION
**Pull request by xla**
Closes #846

### CODE REVIEW

**Review by NunoAlexandre — APPROVED** [review]
:broom: 

It's a sensible thing to do given where we are right now.

**Review by FintanH — APPROVED** [review]
I never did like this trait business :+1:

**Comment by rudolfs** [comment]
Closes: https://github.com/radicle-dev/radicle-upstream/issues/549.

**Review by rudolfs — APPROVED** [review]
Byeee 👋

**Pull request merged**
