### PR TITLE
chore(ci): Warn about focused tests

### PR DESCRIPTION
**Pull request by geigerzaehler**
We fail linting when a test is focused with `.only`.

### CODE REVIEW

**Comment by rudolfs** [comment]
Fixes: #947.

**Review by rudolfs — CHANGES_REQUESTED** [review]
We had a working husky/lint-staged setup which would prevent us even from committing skipped tests. That seems to be broken now (even on master). `eslint-plugin-no-only-tests` was supposed to take care of that, albeit it used to work only on `it.only` and not `context.only`.

Could we get lint-staged working again so we catch the focussed tests even before they reach CI?

**Comment by geigerzaehler** [comment]
> `eslint-plugin-no-only-tests` was supposed to take care of that

I wasn’t aware of that plugin. I’m using it instead now. The only thing that was missing was to add it to `.eslintrc.js`.

**Review by rudolfs — APPROVED** [review]
Neat! 👍

**Review by NunoAlexandre — APPROVED** [review]

**Pull request merged**
