### PR TITLE
fix(ui): list border overflow (#1447)

### LINKED ISSUE #1447: Border radius glitch when hovering over projects in the "Still looking…" section on the Following tab of your profile
image

if you don't see it, it's happening on the corners. some inner element is probably not rounded 
image

### PR DESCRIPTION
**Pull request by finleygn**
Fixes #1447

Border radius of lists now just handled by the parent with overflow, rather than having border radius on children too.

image

### CODE REVIEW

**Review by geigerzaehler — DISMISSED** [review]
Thanks for the contribution!

**Review by xla — CHANGES_REQUESTED** [review]
Thanks for the contirbution. We aim to attribute all contributors properly, see our [DCO](https://github.com/radicle-dev/radicle-upstream/blob/master/DCO). For that could you repush your commit with [signoff](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff).

**Comment by finleygn** [comment]
@xla This projects really cool so happy to help out, learning rust and svelte at the moment so starting out small :)

re-pushed on here and #1468

**Review by xla — APPROVED** [review]
🍤 ✔️ 🍺 ⌚️

**Review by geigerzaehler — APPROVED** [review]

**Pull request merged**
