### PR TITLE
fix: improve pending anchor message

### PR DESCRIPTION
**Pull request by rudolfs**
When the quorum of members have signed a transaction on Gnosis Safe, this transaction still needs to be executed by one of the members manually before it gets submitted to the blockchain. In this case show a different message to the user so they know what needs to be done.

Closes: https://github.com/radicle-dev/radicle-upstream/issues/2092.

Screenshot 2021-09-07 at 18 23 01

### CODE REVIEW

**Comment by rudolfs** [comment]
Does the copy sound good here @brandonhaslegs?

**Comment by brandonhaslegs** [comment]
Can there be more than one pending?

**Comment by brandonhaslegs** [comment]
Maybe "Waiting for a member to execute."

**Comment by rudolfs** [comment]
> Can there be more than one pending?

No.

> As a member what does this look like? It's not clear how's to execute if this is the member view.

This is what a member would see. You only see the anchor stuff if you're a member of the org. Maybe there should be a link to the Gnosis Safe transaction, so that you can execute it?

**Comment by brandonhaslegs** [comment]
> Maybe there should be a link to the Gnosis Safe transaction, so that you can execute it?

Yes plz

**Comment by rudolfs** [comment]
Not enough members have signed:

Screenshot 2021-09-08 at 07 41 00

Quorum has signed, but tx is not yet executed:

Screenshot 2021-09-08 at 07 51 23

"Execute transaction" link goes to:

Screenshot 2021-09-08 at 07 53 14

We can't link to the exact transaction yet, because of https://github.com/gnosis/safe-react/issues/970.

**Comment by brandonhaslegs** [comment]
> Not enough members have signed

Change this text to "Not enough members have signed this anchor." (remove "of the")

**Comment by rudolfs** [comment]
Screenshot 2021-09-08 at 08 46 38

**Comment by rudolfs** [comment]
Now I'm thinking, should this also have a link to the transaction?

`Not enough members have signed this anchor. Sign anchor`

**Comment by brandonhaslegs** [comment]
> Now I'm thinking, should this also have a link to the transaction?

Yes

**Comment by rudolfs** [comment]
I also aligned the wording to match the Gnosis Safe webpage:

Screenshot 2021-09-08 at 09 06 45


Screenshot 2021-09-08 at 09 06 38

**Comment by brandonhaslegs** [comment]
In one of the lines we say "this anchor transaction" and in the other we say just "anchor transaction" Should we add "this" to the other one?

**Comment by rudolfs** [comment]
Done.

Screenshot 2021-09-08 at 09 34 44

**Review by brandonhaslegs — APPROVED** [review]

**Pull request merged**
