### PR TITLE
refactor(ui): use idiomatic async code instead of Promise

### PR DESCRIPTION
**Pull request by geigerzaehler**
We rewrite some code that uses the `Promise` constructor and callbacks to more idiomatic async/await code and log the error that was swallowed previously.

### CODE REVIEW

**Comment by xla** [comment]
What is the signal of that error besides that the project doesn't have a readme? Which is already surfaced in the ui.

**Comment by geigerzaehler** [comment]
> What is the signal of that error besides that the project doesn't have a readme? Which is already surfaced in the ui.

If the project does not have a readme then the function returns early because `path` is `null`. So if `fetchBlob` throws then we have a readme but we failed to fetch it for some reason. In this case we should show an error.

**Review by xla — APPROVED** [review]
🐝 🚭 🈚️ 🏘

**Review by NunoAlexandre — APPROVED** [review]

**Comment by geigerzaehler** [comment]
Merged in 4a6788500722f1144d61e2e0de39e0afc8dc82bb

**Pull request closed without merging**
