### PR TITLE
fix(ui): allow irc:// as external protocol

### PR DESCRIPTION
**Pull request by rudolfs**
If anyone wonders why we passlist: https://security.stackexchange.com/questions/225799/dangers-of-electrons-shell-openexternal-on-untrusted-content.

Closes: https://github.com/radicle-dev/radicle-upstream/issues/917.

### CODE REVIEW

**Comment by xla** [comment]
We might not need this at all as we are going to move away from IRC for our community. @abbey-titcomb Can shed some light.

**Comment by abbey-titcomb** [comment]
Yeah, but we don't have the replacement spun up yet, so I don't see why we should keep thee broken link around. Can sub for Matrix chat once we have it figured out.

**Comment by xla** [comment]
> Yeah, but we don't have the replacement spun up yet, so I don't see why we should keep thee broken link around. Can sub for Matrix chat once we have it figured out.

Because we have to remember to remove the exceptiosn added. Can we assume matrix lands before launch?

**Review by sarahscott — APPROVED** [review]
I think this makes sense for as long as we're using irc.

**Review by xla — APPROVED** [review]
🖖 ☃ 🕕 ✅

**Pull request merged**
