### PR TITLE
fix(ui) prevent images in markdown from overflowing

### PR DESCRIPTION
**Pull request by Tbaut**
A tiny fix to go from:
image

to:
image

### CODE REVIEW

**Review by cloudhead — APPROVED** [review]
:+1:

**Review by MeBrei — APPROVED** [review]
⭐

**Review by xla — APPROVED** [review]
Thanks for this contribution!

🔈 🐔 🌖 🕰

**Review by FintanH — CHANGES_REQUESTED** [review]
Thanks for your contribution! I just wanted to flag that we're changing our licensing language tomorrow to implement a DCO -- more information [here](https://radicle.community/t/radicle-licensing-model/282).

So to preempt this, could we ask you to sign your commits during a `git rebase`:
```
       --signoff
           Add a Signed-off-by: trailer to all the rebased commits. Note that if --interactive is given then only commits marked to
           be picked, edited or reworded will have the trailer added.

           See also INCOMPATIBLE OPTIONS below.
```

I believe running this command `git rebase cf9d719fc747650bcb1eca246f6ec2cb182c6ff3^ --signoff` should allow you to sign off the commit with your name and email.

If you have any issues let me know and maybe we can try to arrange a call to help :grin:

**Comment by Tbaut** [comment]
This seems to have signed-off all the commit between `cf9d719` and the head although it didn't sign the needed one. The last merge into master isn't signed either (a git pull was needed before pushing).
To avoid any headache for such a small contribution I can simply close this PR, commit and sign again, and push it again.

**Comment by FintanH** [comment]
Ah apologies. My git-fu isn't always the strongest! Reopening a new PR sounds good to me. Sorry about the inconvenience, we're going to update our documentation about this ASAP

**Comment by Tbaut** [comment]
All good.

**Pull request closed without merging**
