### PR TITLE
Add base `/` to url

### PR DESCRIPTION
**Pull request by juliendonck**
Fixes an issue that workstreams can't find emoji's because it url based.

### CODE REVIEW

**Comment by rudolfs** [comment]
Unfortunately this breaks emojis in Upstream. Will think about how to fix this properly.

Screenshot 2022-05-17 at 15 07 00

**Comment by rudolfs** [comment]
I see 2 paths forward:
  - we could expose a prop on the Emoji component, something like `export let staticAssetBase = ""`, which would require passing this in at all callsites or
  - we have a `design-system-config.json` file, which could be read in from a default location and could configure app-wide design system things

I kind of like the config file approach, because it would allow us to specify this in one place and we could finally export more complex components that require configuration. E.g. the `Copyable` component, which requires a different implementation depending whether we're running on web or electron.

**Comment by juliendonck** [comment]
I think the config idea is interesting, especially it enabling us more complex components. One thing that occurred to me is that it would require more configuration when others would like to use it, so maybe there is a default in the components so it doesn't need the config or by installing the package it already adds the config. I'm just thinking of noobs like me...

**Comment by juliendonck** [comment]
On the other hand, the staticbase-prop we'd already have done and it would already work :/

**Comment by rudolfs** [comment]
Tried the config file approach, but ran into issues with making a config override in the target project.
Ended up auto-detecting the environment in the Emoji component: https://github.com/radicle-dev/radicle-upstream/commit/c22af1d8b75704dfd84546a937281be6f3f76d35#diff-9ad8586d1b1e592c3f2bcb3133be218c15b3ead50aefb11e733d5922fab61424R20.

**Pull request closed without merging**
