### PR TITLE
refactor(proxy): Introduce SessionContext

### PR DESCRIPTION
**Pull request by geigerzaehler**
*Based on #1064*.

Introduce `SessionContext` and an associated guard for endpoints that require coco to be initialized with an owner and a session to be present.

In a follow-up we will use the `SessionContext` to also assert the presence of an unsealed `BoxedSigner`.

### CODE REVIEW

**Comment by FintanH** [comment]
Could you change the base branch to point to #1064 to make the diff clearer?

**Review by MeBrei — APPROVED** [review]
LGTM!

**Review by FintanH — APPROVED** [review]
LGTM where the G stands for GREAT

**Review by xla — CHANGES_REQUESTED** [review]
@geigerzaehler @MeBrei and I discussed the design offline and a lot of follow-ups are captured which will change this PR.

**Comment by FintanH** [comment]
> discussed the design offline and a lot of follow-ups are captured which will change this PR.

Sweet, looking forward to seeing these :grin: :eyes:

**Pull request closed without merging**
