### PR TITLE
fix: style forms to match new design system

### PR DESCRIPTION
**Pull request by juliendonck**
Updated the forms & drop downs to match the design system.

### CODE REVIEW

**Comment by juliendonck** [comment]
@rudolfs I didn't name my commits properly, but they will get squashed, right? 😇

**Comment by rudolfs** [comment]
@juliendonck yeah, no worries!

btw. I think you shouldn't spend too much time on styling the dropdown, as it will be replaced with a fully custom one in #292.

**Comment by juliendonck** [comment]
@rudolfs I see. But I've noticed that it's still not entirely based on the new design. SHould I just wait for that one to land? Or should I pull that one and fix it?

**Comment by rudolfs** [comment]
@juliendonck yeah, you're right, it is not exactly as per new design. I made it fit the existing design so it would not stick out.

We should aim to make design changes in one go: adjust the component and make sure that it works in all places where it is already used.

I would wait for #292 to be merged before working on the dropdown.

**Comment by juliendonck** [comment]
@rudolfs I guess we can wait for it to be merged, pull master into this one and then fix it here.

**Comment by rudolfs** [comment]
@juliendonck just realised that there will be more work required to get the new dropdown working which is beyond the scope of #292. So I guess we can just style the existing one for now.

**Comment by juliendonck** [comment]
@rudolfs good catch. Removed those.

**Pull request merged**
