### PR TITLE
fix(ui): show search input hint on empty input

### LINKED ISSUE #976: Keyboard hint appears *after* user types
The keyboard hint should be visible *before* the user types anything into the search box.

Since we already have the keyboard hint in there, should we also remove the "Paste it here..."?

paste

### PR DESCRIPTION
**Pull request by MeBrei**
Closes #976

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]

**Review by NunoAlexandre — APPROVED** [review]

**Comment by sarahscott** [comment]
Looks good! I want to make sure this is the desired behavior - is the hint supposed to disappear as soon as the user types? Wouldn't we want the hint to be there when they finish typing, so they can use it?

**Review by sarahscott — APPROVED** [review]

**Comment by rudolfs** [comment]
> Looks good! I want to make sure this is the desired behavior - is the hint supposed to disappear as soon as the user types? Wouldn't we want the hint to be there when they finish typing, so they can use it?

AFAIK, that's how @juliendonck implemented it first.

I think I'd also find it more intuitive if it was always there, but I wonder whether it would not conflict with the icons of the *waiting* and *validated* input states.

**Comment by rudolfs** [comment]
A good example where the show/hide logic doesn't sense to me is the password input fields:
pw

**Comment by juliendonck** [comment]
> Looks good! I want to make sure this is the desired behavior - is the hint supposed to disappear as soon as the user types? Wouldn't we want the hint to be there when they finish typing, so they can use it?

You make a good point and I had tried to do it as you suggested, but it would be a much more involved solution. And I felt is wasn't warranted the time and effort. 

The reason it's so much more involved is that it would need to work with the validation on the one hand but we'd also have to resize the input text field depending on the size of the hint.

So even though it's not perfect, I think it does the job for now.

**Pull request merged**
