### PR TITLE
update radicle-link and cargo dependencies

### PR DESCRIPTION
**Pull request by geigerzaehler**

### CODE REVIEW

**Review by rudolfs — APPROVED** [review]
utACK

**Comment by geigerzaehler** [comment]
I’m putting this on hold until the [backwards compatibility issues](https://lists.sr.ht/~radicle-link/dev/%3CCAH_DpYRRkDEpQB%3DVa%3DhHVaubbk8A2XR-tFzB7RDWzyzsT5Vpew%40mail.gmail.com%3E)  with collaborative objects are resolved

**Comment by rudolfs** [comment]
> I’m putting this on hold until the backwards compatibility issues with collaborative objects are resolved

Good catch!

**Comment by geigerzaehler** [comment]
I’ve updated to today’s cycle release that fixes the compatibility issue.

**Review by rudolfs — APPROVED** [review]

**Pull request merged**
